percy/percy-agent

.circleci/config.yml
.vscode/launch.json
package-lock.json
package.json
src/commands/percy-command.ts
src/services/build-service.ts
test/commands/percy-command.test.ts
test/services/agent-service.test.ts
test/services/build-service.test.ts

Update percy-client to v3 which no longer needs PERCY_PROJECT environment variable to create a build.

Update percy-client to v3

---

package-lock.json
package.json

Patches this issue https://github.com/GoogleChrome/puppeteer/issues/2888 that we have been receiving.

Bump to puppeteer 1.10.0 

---

src/services/asset-discovery-service.ts

Sometimes a new URL loaded into a reused Puppeteer page fails to trigger network events when the contents of the page is changed and in turn misses discovering assets.
This issue is observed when having several snapshots in a row with: `http://localhost/#/`
Originally we'd setup the page to be reused in this way between snapshots because there's a performance hit of around 80-90ms to open a fresh page in Puppeteer.
It's safe to strip anchor tags completely only for asset discovery because the settled DOM has already been captured before this point.

Strip anchor tags for asset discovery

---

src/services/agent-service.ts
src/services/snapshot-service.ts

Companion PR to https://github.com/percy/percy-js/pull/45
See build info of https://percy.io/test/test/builds/1232218  for an example of the new user agent string.

Pass client and environment info through to percy-js

---

src/percy-agent-client/percy-agent.ts

Fix typo in private method name

---

src/services/asset-discovery-service.ts

With resource hints in asset discovery, there is no guarantee that
the request will result in content being responded.
Add `shouldRequestResolve` method to determine if a request should
continue or be aborted in pupetteer.
If an asset is a resource hint then there is a purpose within the
request header, if this exists and is of a specific value we can
detirmine the request shouldn't resolve
Assets in resource hints are not necessary for the page to render
correctly they are there to give the browser better performance in
production applications/websites for the purpose of percy this assets my
never be requested thus storing unused asssets.
Fixes #53

Reject resource hint requests

---

package-lock.json
src/percy-agent-client/percy-agent.ts
src/percy-agent-client/serialize-cssom.ts
test/percy-agent-client/serialize-cssom.test.ts
test/percy-agent-client/test.html

Serialize CSSOM into DOM

---

package-lock.json
package.json

Puppeteer 1.12.0 is causing us issues

Lock specifically to puppeteer 1.11.0

---

src/services/response-service.ts

Break out each reason we'd skip an asset from being discovered and output that to the log

Asset Discovery Skip Reason

---

src/utils/sdk-utils.ts

Set maxContentLength to 100mb to allow DOM snapshots over 10mb (the current default value).
Related: https://github.com/percy/percy-puppeteer/issues/70

Support post requests to the agent that are over 10mb

---

package-lock.json
package.json

See https://github.com/percy/percy-agent/issues/154

fix: Remove @oclif/errors from devDependency list

---

package-lock.json
package.json

fix: Lock `@oclif/command` to 1.5.10 to avoid `MaxListenersExceededWarning`

---

README.md
src/commands/exec.ts
src/commands/finalize.ts
src/commands/snapshot.ts

Reformats some wording, adds context around finalizing a build.

fix: Improved readme and help text

---

package-lock.json
package.json

There's a major security issue in older versions of axios, which is what we use for network requests in Agent. This will close this: https://github.com/percy/percy-agent/network/alert/package-lock.json/axios/open

fix: [Security] Upgrade axios

---

test/integration/agent-integration.test.ts

This PR adds a little coverage for the `postSnapshot` util we use in our SDKs. This implementation matches the behavior of the puppeteer SDK (and almost all other SDKs)

test: Update integration test to use `postSnapshot` util

---

package-lock.json
package.json
src/percy-agent-client/dom.ts
test/integration/agent-integration.test.ts
test/integration/testcases/stabilize-dom.html
test/percy-agent-client/dom.test.ts

This will capture the selected values from `<select>` elements.

feat: Serialize select elements values

---

.circleci/orb.yml

Added Github repo to Orb description
Resolves : #356

docs: Added github repo to orb description

---

.circleci/orb.yml

Provides a more detailed description to the user of what finalized
is used for in the orb.

build: [Orb Enhancement] Detail usecase.

---

.circleci/orb.yml

Pull request for [Orb Enhancement] Add missing job description. #359

fix: Adding missing job description.

---

.circleci/orb.yml

build: Add tag parameter for Docker image

---

src/commands/start.ts
src/commands/stop.ts
yarn.lock

These shouldn't be hidden, they're useful and recommended to use in specific cases.

feat: Unhide `start` and `stop` commands
