test/services/agent-service.test.ts
Chai was not happy about seeing an uncaught error in the `end` block of a request, but we are explicitly expecting an error for this particular test.
Moving to a `catch` block makes the test more reliable and also removes a deprecation that will make this test fail every time in future version of chai.
=> Fix flakey test by using catch instead of end

package-lock.json, package.json, src/services/agent-service.ts, src/utils/configuration.ts, test/support/.percy-invalid.yml, test/support/.percy.yml, test/utils/configuration.test.ts
This PR allows the user to create a `.percy.yml` file like this:
```yaml
version: 1
snapshot:
widths: [375, 1280]
min-height: 1024
enable-javascript: false
```
This configuration will be picked up as the default options when taking a snapshot. This is particularly useful for setting default snapshot widths across for your entire build.
The configuration file needs to be created in the directory the `percy` command is being run. For now, `.percy.yml` is hardcoded as the filename. Potentially in the future we'll have a flag which will allow you to point to any file on disk to be used for the configuration.
=> Introduce .percy.yml configuration file for setting snapshot defaults

README.md, src/commands/exec.ts, src/commands/finalize.ts, src/commands/percy-command.ts, src/commands/start.ts, src/commands/stop.ts, src/percy-agent-client/percy-agent-client.ts, src/percy-agent-client/percy-agent.ts, test/commands/finalize.test.ts, test/commands/percy-command.test.ts, test/percy-agent-client/percy-agent.test.ts
When a token is provided, we create a build and run the subprocess.
```bash
$ PERCY_TOKEN=abc percy exec -- echo "hello"
[percy] created build #3209: https://percy.io/test/test/builds/1146012
[percy] percy has started.
hello
[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.
[percy] finalized build #3209: https://percy.io/test/test/builds/1146012
$ echo $?
0
```
When a token is not provided, we warn the token is missing and continue to run the subprocess.
```bash
$ PERCY_TOKEN= percy exec -- echo "hello"
›   Warning: Skipping visual tests, You must set PERCY_TOKEN
hello
$ echo $?
0
```
Pending an update to the Cypress SDK itself, this will help resolve https://github.com/percy/percy-cypress/issues/3
=> Gracefully handle missing tokens

src/services/asset-discovery-service.ts, src/utils/unique-array.ts
Ensure resources are unique by `resourceUrl` specifically not by the whole resource object.
This bug has allowed some duplicated resources through to our API which results in an error like this:
```
[percy] StatusCodeError 400 - {“errors”:[{“status”:“bad_request”,“detail”:“Attempted to upload multiple resources with the same resource-url: \nhttps://x.com/y.jpg”}]}
```
Resources like this have the same `resourceUrl` but some other bit of the resource object was different and so it was allowed to be included.
=> Ensure resources are unique by resourceUrl

src/services/asset-discovery-service.ts
`isNavigationRequest` is true on more than one page load sometimes and that causes a loop of dom injection. This avoids that by checking the url against the rootResourceUrl instead.
=> Fix asset discovery loop timeout

src/services/snapshot-service.ts
Resolves [this clubhouse story](https://app.clubhouse.io/percy/story/2508/percy-agent-default-widths) by simply sending `null` widths onto our API, which in turn decides what the defaults are.
I've tested this and not specifying widths results in our API defaults and specifying widths continues to work.
=> Remove default widths and allow our API to select them instead

src/services/asset-discovery-service.ts
This is OK because the fully loaded DOM is already captured and we should have all the information required to watch the network as the page loads and capture resources.
It should yield a bit of a performance boost and help pages settle sooner but I haven't done any performance testing on this.
I have tested this on local and live websites and all assets are captured as you would expect.
=> Disable JavaScript when loading pages for asset discovery

src/percy-agent-client/percy-agent.ts, src/percy-agent-client/snapshot-options.ts, src/services/agent-service.ts, src/services/asset-discovery-service.ts, src/services/snapshot-service.ts, test/percy-agent-client/percy-agent.test.ts
I've added some test coverage too for when snapshot calls are made with options.
This PR also renames `enableJavascript` to `enableJavaScript` but supports both. Eventually we should deprecate `enableJavascript`.
=> Enable JS in asset discovery when the snapshot itself has JS enabled

src/services/asset-discovery-service.ts
Caught and verified fix while working on `@percy/puppeteer`.
=> Add missing block return, avoid trying to double-handle the request

src/services/agent-service.ts, src/services/asset-discovery-service.ts, src/services/snapshot-service.ts
This PR introduces no functional changes, and is only a small refactor on how we pass around things like `widths` and `enableJavaScript`.
I think this variant helps keep things a little more consistent throughout the codebase, and we'll need it in any case as part of the responsive asset work, which requires `discoverResources(...)` to be aware of the requested snapshot `widths`.
=> Use SnapshotOptions for passing around things like enableJavaScript

src/utils/logger.ts
Because of an underlying quirk in the `winston.Logger` implementation, if we pass `null` for the callback parameter, the `meta` parameter will get ignored. This is because their code relies on the length of the argument list passed in, and even a `null` parameter counts towards the length; for details see their code in: https://github.com/winstonjs/winston/blob/2.4.4/lib/winston/logger.js#L582-L586
Passing through the `callback` only if it is defined makes it so that our `meta` parameter is treated correctly and the `meta` info is output to the log.
=> Fix how we pass parameters through to profile

src/services/response-service.ts
A small optimization to avoid overly taxing the hard drive and saving ourselves some work. This becomes more important with the parallel resource discovery that we're introducing in https://github.com/percy/percy-agent/pull/81, which makes it much more likely that we will try to copy something we've already copied.
=> Skip copying file if we seem to have already made a copy

src/services/agent-service.ts, src/services/build-service.ts
CI and percy run on seperate status checking in PR, so we don't need
percy build to execute for the test suite to run.
This allows builds to proceed even if percy is down, this allows the
setting of proceeding with the build to be done through percy build
hooks rather than in the CI.
=> Fix percy build error breaking ci

src/utils/sdk-utils.ts
The one debatable choice in this change is that I'm using the logger we use in `@percy/agent` to emit logs that will come from the SDK process. I think this is preferable to changing the code to pass through the error and then updating all the SDKs to log the error, plus putting it here makes it possible to use our nice `logger`.
wdyt @Robdel12 @djones ?
=> Add debug logs when posting a snapshot via sdk utils fails

src/percy-agent-client/serialize-cssom.ts
When serializing the CSSOM we're currently creating a `<style>` tag and appending it to the `<style>` tag that owns the CSSOM styles. This change ensures the serialized CSS from the CSSOM is appended to the `<style>` tag which the styles originated from rather than nesting `<style>` tags.
You can see this causing an issue in this example repo: https://github.com/montezume/percy-puppeteer-emotion/pull/1
This build was ran on that repo with this change: https://percy.io/robdel12/the-garbage-collection/builds/1470912 
**Before**
**After**
=> Append CSSOM to owner node

src/percy-agent-client/percy-agent.ts, test/integration/agent-integration.test.ts, test/integration/testcases/stabilize-dom.html
Previously we were only serializing input elements. This adds textareas to that list. They're a bit of a special element. I couldn't get it to work locally when setting the `value`, `text`, or anything else besides `innerText`. Which seems fine. 
[I splunked through how jQuery does it and they're setting the `textContent`](https://github.com/jquery/jquery/blob/master/src/manipulation.js#L334). I created a little jsbin to illustrate the differences: https://jsbin.com/hiquvuzele/1/edit?html,js,output
I have no issues changing `innerText` to `textContent` if that's something we want to do.
=> Serialize textareas for snapshots

src/services/asset-discovery-service.ts, src/services/response-service.ts
As suggested by @Robdel12 , this makes the logs when snapshotting multiple widths in parallel a little bit more useful. Right now they look like:
```
[percy] processing response: https://10.43.238.110:3000/innovate-blog-staging
[percy] Skipping [is_root_resource]: https://10.43.238.110:3000/innovate-blog-staging
[percy] processing response: https://10.43.238.110:3000/innovate-blog-staging
[percy] Skipping [is_root_resource]: https://10.43.238.110:3000/innovate-blog-staging
[percy] processing response: https://10.43.238.110:3000/innovate-blog-staging
[percy] Skipping [is_root_resource]: https://10.43.238.110:3000/innovate-blog-staging
```
There is, of course, the somewhat unfortunate thing of passing around the width _just_ for logging. But worth it for better logging, I think.
=> Add width of snapshot to resource logging

package-lock.json, package.json
I ran the integration tests with this change a handful of times and they all succeeded. Looks like whatever was the issue we were having with Puppeteer v1.12 is gone now. Yay.
=> Bump Puppeteer to version 1.13

src/services/asset-discovery-service.ts
Suggested by a conversation on the Puppeteer issue referenced from https://github.com/percy/percy-agent/issues/92, this change will make asset discovery a little bit more robust, by only trying process an asset once the request for it has succeeded in the browser.
=> Process assets on 'requestfinished' instead of 'response'

package-lock.json, src/percy-agent-client/percy-agent.ts, src/percy-agent-client/serialize-cssom.ts, test/helpers/html-string.ts, test/percy-agent-client/percy-agent.test.ts, test/percy-agent-client/serialize-cssom.test.ts
This solution works in the general case, and this PR adds a test making sure that the behavior doesn't regress.
It is important to note, however, that in cases of malformed or otherwise degenerate underlying DOM, the clean up might not work perfectly, leaving behind pieces of serialized CSS.
I don't love having to do things this way -- it would be much cleaner to make a deep copy of the DOM and operate always on that. On the positive side, this implementation feels robust and understandable enough that it should be fairly maintainable.
Thoughts?
=> Carefully undo our serialized CSSOM from the customer DOM. Add tests.

src/percy-agent-client/percy-agent.ts, src/percy-agent-client/serialize-input.ts, test/percy-agent-client/percy-agent.test.ts, test/percy-agent-client/serialize-input.test.ts
I've also made the logic of the serialization a little bit more conservative, doing the serialization only when it seems to be necessary. The drawback of that is that it makes the implementation a little bit less obvious (and thus more likely to contain a bug).
Finally, this change also moves input serialization into its own file (and associated test), similar to the structure we have for the CSSOM serialization code.
(This PR is the follow-up I promised in https://github.com/percy/percy-agent/pull/109)
=> Clean up serialized inputs after snapshotting

package.json
This adds a `browser` field to the agent `package.json` so bundlers like webpack, parcel, rollup, etc won't bundle our node process code with the code we inject into the browser. This will solve this issue: https://github.com/percy/percy-cypress/issues/58 so folks no longer need to modify their webpack config due to errors originating in agent.
=> Add browser field so bundlers don't bundle node files

.circleci/config.yml, src/commands/health-check.ts, src/utils/health-checker.ts, test/commands/health-check.test.ts
In some instances it's helpful to have a CLI command that runs a check to make sure the Percy process is running. This will be especially helpful in the Cypress SDK where we're having struggles with providing a nice way to run a CLI command with the SDK:
- https://github.com/percy/percy-cypress/pull/67
- https://github.com/percy/percy-cypress/pull/69
- https://github.com/percy/percy-cypress/pull/72
`$ percy health-check` or `$ percy health-check -p 5502`
=> feat: Add `healthcheck` command

package.json
Looks like we need to also introduce rollup to bunndle all of the files together into a single file when we introduce the `browser` field. Otherwise bundlers are going to fall over at the bad `require` file paths.
=> fix: Revert & remove `browser` from `package.json`

src/index.ts
@percy/agent is sometimes imported like this in our SDKs:
```javascript
import PercyAgent from '@percy/agent'
```
At which point the default export is imported. This export is intended to run in a browser and everything in the `src/percy-agent-client` directory is built to expect this.
As we've built out our SDKs we found that @percy/agent is also quite useful for centralizing SDK utility functions. We previously had been distributing these util functions through the default export, so you can go:
```javascript
import { agentJsFilename, isAgentRunning, postSnapshot } from '@percy/agent'
```
The problem with that is the util code would import other libraries, such as Winston, which are entirely designed to run on Node and not in a browser.
This PR simply removes the node-specific code from …
=> fix: avoid node-based sdk-utils in default export for package

src/commands/exec.ts, src/commands/snapshot.ts, src/commands/start.ts, src/services/constants.ts, src/services/static-snapshot-options.ts, src/services/static-snapshot-service.ts, test/commands/snapshot.test.ts
This PR adds a hidden snapshot command, and a stubbed static snapshot service that will be fleshed out in a future PR.
This also includes tests for the snapshot command.
=> feat: Add hidden snapshot command for future implementation

src/percy-agent-client/percy-agent.ts, src/percy-agent-client/serialize-cssom.ts, src/percy-agent-client/serialize-input.ts, test/integration/agent-integration.test.ts, test/integration/testcases/stabilize-cssom.html, test/integration/testcases/stabilize-dom.html, test/percy-agent-client/percy-agent.test.ts, test/percy-agent-client/serialize-cssom.test.ts, test/percy-agent-client/serialize-input.test.ts
Given this JSBin: https://jsbin.com/?html,console,output
When we serialize the CSSOM into the `<style>` tag that the in-memory styles own and then _remove_ those styles, it triggers `deleteRule` on those styles in the CSSOM. Which means we're removing the text we injected AND all of the styles that live in memory. This breaks their app.
With the input cleaning, when we remove the value or checked attribute on the element, it's possible those elements lose their values entirely. For example, when we remove the `checked` attribute from checkboxes in the customers DOM, this will make the checkbox _no longer checked_, which is changing the state of their application. It would be better, in this world without an AST, to leave the mutations in place. Removing the mutations causes more issues …
=> fix: Revert DOM clean up methods

rollup.config.js
We rely on the agent code we inject into the browser to be globally available on the window. There's no reason we need to distribute the code we inject into the browser as a universal module.
There are some cases where the site we inject the current agent code into that defines one of these modules (could be cjs, amd, or even the es6 module format). When that case happens it breaks out SDKs because `PercyAgent` is not defined.
This commit changes the build to output an immediately invoked function, which will always expose agent as a global.
=> fix: Build `PercyAgent` code that's inject in browser as iife

package-lock.json, package.json, rollup.config.js, test/integration/agent-integration.test.ts
Looks like `iife` from rollup isn't exposing agent as a global. We
need `window.PercyAgent =` not `var PercyAgent=`
=> fix: Revert change to module bundling

rollup.config.js
Second time is the charm right? Setting `extend: true` in the rollup config allows
the bundler to extend the global namespace (window).
So, the output now looks like `this.PercyAgent = ` (where `this` is the
window object)
I cut a beta release of this and tested it on the various SDKs (btw, we need a better process for this):
- https://github.com/percy/percy-cypress/compare/rd/agent-beta-4.4
- https://github.com/percy/percy-puppeteer/compare/rd/agent-beta-4.4
- https://github.com/percy/percy-nightwatch/compare/rd/agent-beta-4.4
- https://github.com/percy/percy-webdriverio/compare/rd/agent-beta-4.4
- https://github.com/percy/percy-nightmare/compare/rd/agent-beta-4.4
- https://github.com/percy/percy-protractor/compare/rd/agent-beta-4.4
- …
=> fix: Expose `PercyAgent` as a global always

package-lock.json, package.json, test/integration/agent-integration.test.ts
The dependencies that were pulled from the `npm` registry are back. So this means CI will run again thanks to: https://github.com/jfhbrook/node-ecstatic/pull/256
=> chore: Bring back commented out tests (due to `http-server`)

src/commands/snapshot.ts
```
~/Code/percy-agent(david-jones/show-snapshot-command ✗) ./bin/run --help
An agent process for integrating with Percy.
VERSION
@percy/agent/0.4.4 darwin-x64 node-v8.10.0
USAGE
$ percy [COMMAND]
COMMANDS
exec      Start and stop Percy around a supplied command
finalize  finalize a build
help      display help for percy
snapshot  Snapshot a directory containing a pre-built static website
```
^ now shows up in help like this ^ and will also show up on the readme on release.
=> fix: Make `snapshot` command visible

test/services/static-snapshot-service.test.ts
Resolves this warning:
```
Warning: superagent request was sent twice, because both .end() and .then() were called. Never call .end() if you use promises
Warning: .end() was called twice. This is not supported in superagent
superagent: double callback bug
```
=> test: Avoid superagent double callback warning

.circleci/config.yml
We recently acquired the ["percy" package on npm](https://www.npmjs.com/package/percy). This will allow us to have extra nice commands like `npx percy snapshot _site/`.
To start we've decided to dual publish `@percy/agent` and `percy` packages. It's a wee bit tricky to test this run but this is my best guess at making it work.
P.S. a big thank you to @mauricebutler for graciously handing over ownership of the `percy` npm package.
=> build: dual release `@percy/agent` and `percy` packages

src/services/asset-discovery-service.ts, test/integration/agent-integration.test.ts
This is so the asset discovery service doesn't fail to capture assets for snapshots that are done on invalid HTTPS sites. Without this the assets would be missing from the snapshots (as seen in this PRs first commit Percy build).
The test that's included here will be missing styles if the snapshot fails -- but the test suite will not fail. The Percy build _will_ have diffs though.
=> fix: Disable HTTPS errors for asset discovery

src/percy-agent-client/dom.ts, test/integration/agent-integration.test.ts, test/percy-agent-client/dom.test.ts
Previously, if the `value` attribute was present in the DOM, we didn't serialize the elements `value` _property_ to the attribute. There's no reason for us to make this check. it's 100% safe for us to always apply the property value as an attribute on the DOM node. 
I also noticed there's a bug with the switch where we didn't have a `break` on `textarea`s, so we were always adding an invalid `value` attribute.
=> fix: Always apply form elements value property as an attribute

src/services/agent-service.ts, src/services/constants.ts, src/services/response-service.ts, test/integration/testcases/exceeds-resource-size-limit.html
This PR:
* Skips resources and snapshots early on that are destined to fail on upload anyway
* Reduces noise in debug logs with large dom snapshots 
* Debug logs when and why we're skipping a given resource or snapshot
You'll see logs like this in the integration test run:
```
[percy] snapshot skipped[max_file_size_exceeded]: 'Test case: exceeds-dom-snapshot-size-limit.html'
```
That is excepted behavior. Graceful handling of a large DOM and warning you about it.
This PR also drops large resources gracefully and early. If you have `LOG_LEVEL=debug` set you will see in the logs something like this:
```
[percy] Skipping [max_file_size_exceeded_21141605] [1280 px]: http://localhost:8000/20mb.png
```
=> feat: Improved large resource handling

src/services/static-snapshot-service.ts
This will turn a snapshot name from `http://localhost:5339/index.html` to `/index.html`
This is so if anyone changes the hostname or port, it doesn't mess up their snapshot baseline
=> fix: Strip host from static snapshot names

.circleci/config.yml
This PR splits the various test commands we run in CI into their own specific (and labeled) steps. I believe a lot of the flakey tests we were seeing were due to all the tests running right after each other. This could cause race conditions where Karma is still cleaning up and freeing up resources when the puppeteer browser was launching and starting.
I've noticed the puppeteer integration tests are a little faster (from the mocha reporter) after this change. 
This is the first stab at fixing our flakey tests. I want to try and make small & incremental changes so we know what the root cause was as we work through it.
=> ci: Separate test commands to different steps

test/integration/agent-integration.test.ts
I'm not really a fan of loops in tests and this is a good example for why. The two large resource snapshots in that loop took `2055ms` & `2186ms`, which takes almost all of the timeout. So then the following 3-4 files in that loop have like `400ms` to work with to do everything. Sometimes they can complete, other times it fails because it hit the timeout.
This commit makes all of the tests their own asserts so they get a full 5000ms
to work with individually.
=> ci: Remove loop over test cases for explicit test cases

src/services/static-snapshot-service.ts
I've been seeing a lot of errors like:
```
Error: Execution context was destroyed, most likely because of a navigation.
```
This happens because we try to start altering the page (by injecting our JS) before everything is settled down. This change won't promise the page has actually loaded (that's very hard to determine) but it will wait for most network requests to resolve before trying do anything.
=> fix: Static service Wait for network idle

src/utils/sdk-utils.ts
In in the config refactor we're accidentally POST'ing to the health check endpoint, which 404s
Will add tests in a follow up PR
=> fix: `POST` snapshots to the right endpoint

src/services/static-snapshot-service.ts
This makes it so we no longer get redirected from the URL we visit to another one. That usually results in an error, which fails the test suite.
This also adds some try/catches around parts of the snapshot that could fail with helpful error messages
=> fix: Reject redirected requests for static snapshots

src/services/configuration-service.ts
When users are having issues with their config file in support it would be helpful to log the error that's being caught in the config service. I also added another debug log that logs out the directory we'd be expecting the `.percy.yml` file to be.
=> fix: Log error if there is one from the config service

package-lock.json, src/percy-agent-client/dom.ts
This is so we can properly capture HTML content in textareas (which is common with WYSIWYG editors) 
Will this have any impact on non-HTML content? Or will `innerHTML` work as expected?
=> fix: Use `innerHTML` rather than `innerText` for textareas

.circleci/config.yml, package-lock.json, package.json
v1.5.17 introduces type changes that breaks our build (even though the code is fine and the same): https://github.com/oclif/command/compare/v1.5.16...v1.5.17
Until we can unbreak TS, we'll stick to this version.
=> fix: Pin `@oclif/command` to `1.5.16`

package.json, src/commands/exec.ts, src/commands/snapshot.ts, src/commands/start.ts, src/configuration/asset-discovery-configuration.ts, src/configuration/configuration.ts, src/services/asset-discovery-service.ts, src/services/configuration-service.ts, src/services/response-service.ts, test/integration/agent-integration.test.ts, test/integration/testcases/alternate-hostname.html, test/integration/testcases/vue.svg, test/services/configuration-service.test.ts, test/support/.percy.yml
Adds support for allowed hostnames that assets should be captured from.
If a hostname is specified, any requests to assets on that hostname will be captured, and they'll be uploaded to Percy's API as snapshot resources.  During rendering time, **http** requests to the captured asset's url will be hijacked, and the captured resource served. 
Hostnames can be provided either with the `-allowed-hostname` or `-h` flag, or they can be specified in the `.percy.yml` file as an array under agent -> asset-discovery -> allowed-hostnames.
The main function is tested with the new alternate-hostname integration test. It loads a vue.svg file from a hostname of localhost.me. Localhost.me resolves to 127.0.0.1, so we can serve it from our local dev/CI environment, and be sure that the captured asset is …
=> feat: Support capturing assets from allowed hostnames

src/commands/exec.ts, src/commands/percy-command.ts, test/commands/percy-command.test.ts
When running `percy exec` with a command that causes the process to hang, terminating the process causes builds to get stuck in a receiving state due to the build never finalizing.
Add [signal handlers](https://nodejs.org/api/process.html#process_signal_events) for `SIGHUP`, `SIGINT`, and `SIGTERM` to stop and finalize the build.
Multiple signals are sometimes sent and cause the stop method to get called multiple times. This didn't seem to effect finalizing builds, but caused noisy output in the terminal. An instance property, `exiting`, is used to bail out of the stop method when it has already been called. This also prevents secondary events from exiting before the first event has finalized the build.
I also corrected a check for `percyEnabled` which treated the property as a getter …
=> fix: Stop and finalize build on exec termination

src/configuration/snapshot-configuration.ts, src/services/agent-service.ts, test/services/configuration-service.test.ts, test/support/.percy.yml
Enabling JavaScript must be done on a per-snapshot basis and in rare cases where the user needs to enable it for every snapshot, it becomes tedious to add it to every snapshot call.
Add an `enable-javascript` option to the configuration file to enable setting this option for all snapshots in a single setting.
I know we don't recommend setting this option _normally_, however if needed it can be a pain to set this for every single snapshot.
=> feat: Add configuration option to enable javascript

package.json, src/services/response-service.ts, src/utils/domain-match.ts
When the subdomain of a hostname is variable, not known, or has many other subdomains, it is more concise to use a wildcard subdomain.
Attempted to use [`domainMatch`](https://www.npmjs.com/package/domain-match) to compare the resource hostname with the allowed hostnames. However internally, the package uses `parsedURL.host` which contains the port number and causes the check to fail. [The source code](https://github.com/palanik/domain-match/blob/master/index.js) was fairly small and straightforward, so I copied it here and adjusted it to use `hostname` which does not contain the port number.
Copying the small util here also made typescript happy about missing type defs.
=> feat: Allow wildcard hostnames

src/services/configuration-service.ts, test/services/configuration-service.test.ts
This PR makes it so you can pass an `-h` flag, and that'll get applied _along_ with the
hostnames specified in the `.percy.yml`.
=> fix: Concat hostname option from CLI & config file

package.json, src/services/response-service.ts, test/integration/agent-integration.test.ts, yarn.lock
This PR introduces the ability to capture assets that are discovered, but have a redirect chain. Currently agent will skip these assets since it's not super easy to follow the chain all the way through and then capture that asset in Puppeteer.
The redirected resources are captured by requesting the redirected URL with `axios` from Node. This will properly follow the redirect chain for us, then we save the response body of that request as the original request URL (so it proxy's correctly in our rendering env).
While doing this I refactored the methods for capturing resources to their respective paths now. Normal assets from the asset discovery service using puppeteer now process their resource and redirected resources are not processed via Node.
=> feat: Capture redirected assets 

src/services/agent-service.ts, test/integration/agent-integration.test.ts
If you pass an empty array from and SDK, the asset discovery service blows up. We should just fall back to the default widths
=> fix: Check for widths array length so empty arrays are never used

src/services/agent-service.ts, src/services/snapshot-service.ts
While debugging some percy CSS weirdness I thought it would be pretty nice to see in the logs when this is created and if its skipped, why?
=> fix: Add Percy specific CSS to root resource after asset discovery

src/services/response-service.ts, test/integration/agent-integration.test.ts
Turns out redirected assets that 404 can break asset discovery, who knew? :trollface: 😆 
This PR wraps the network call in try/catch (like it always should have been) and handles redirected assets that 404 properly now.
=> fix: Handle 404 errors when capturing redirected assets

src/commands/exec.ts, src/commands/percy-command.ts, src/commands/snapshot.ts, src/commands/start.ts, src/services/process-service.ts
This started out as a fix for #340, to ensure that when agent is terminated, the PID file is always cleaned up. The approach made it easy to preemptively fix a couple of other bugs as well.
The `start` and `exec` commands shared similar startup behavior, but `exec` had better stop behavior by ensuring it is only ever stopped once (due to multiple events). The better behavior from the `exec` command was DRY'd up and moved into the base `PercyCommand` class.
We can then take advantage of inheritance to clean up the PID file whenever the new `stop` method is called. This created an error when the PID file was already cleaned up, so I split up the existing logic to suppress file-not-found errors.
The common `start` and `stop` methods made it possible for the static snapshot command to also …
=> fix: Cleanup on stopping agent

src/services/image-snapshot-service.ts
During image upload, If an error occurs after starting a build, but before finalizing, the build will get stuck waiting for snapshots.
Rather than try-catching the entire method, the try-catch can be wrapped around only the section between creating and finalizing a build. The try-catch is used instead of chaining a `.catch` onto the promise in case the `reduce` callback throws during argument evaluation.
=> fix: Restrict try-catch in upload command so build can be finalized

.ci.percy.yml, src/services/image-snapshot-service.ts, src/utils/configuration.ts
By default, the `deepmerge` package will merge nested arrays. When merging default options with overrides, this had the effect of merging default widths with user-defined widths.
Pass an `arrayMerge` option that will overwrite default arrays with new arrays instead of merging them.
Added a `widths` option to our test config to verify that we should only see `375` and `1200` widths and _not also_ default `1280` widths. Due to this, all of our snapshots have a new width that needs to be approved.
=> fix: Config array merging

src/commands/exec.ts, src/commands/health-check.ts, src/commands/snapshot.ts, src/commands/start.ts, src/commands/stop.ts, src/commands/upload.ts, src/utils/configuration.ts, test/utils/configuration.test.ts
As #393 pointed out: the CLI flags always take precedence over config file options, but the CLI flags are defaulting to their intended defaults now, therefore the defaults are overriding options specified in the config file. 
Remove the oclif defaults and allow those flags and args to default to `undefined`. Since our own config util handles undefined options, there are no regressions and we can still support explicitly passed defaults. However we lose the defaults being included in the `--help` output. The descriptions of effected flags and args have been updated to manually interpolate the eventual default.
Unit tests for the configuration util were added to verify that it was indeed correctly merging configs in preference of: args & flags > config file options > defaults. Tests that …
=> fix: Config default overrides

src/services/image-snapshot-service.ts
Adds to the environment info section for builds when the upload command is used.
=> feat: :sparkles: Add client info for upload command

src/services/asset-discovery-service.ts
There's a chance an error happens and then the page is never cleaned up. This
hangs the process open for ever.
=> fix: Always release puppeteer page in asset discovery

.circleci/config.yml, package.json, test/integration/agent-integration.test.ts
As we've added more features to agent our testing config has been creaking a bit. This doesn't fix our testing woes we're feeling, but it does make it so all of the snapshots kicked off from CI in this repo are combined into the same Percy build. This will prevent this 2 snapshot build from eventually trolling our baseline:
We add the node version to the snapshot name to prevent duplicates.
CircleCI commands are awesome! https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21 You can combine many steps together to reuse across jobs (which is exactly what I did)
=> ci: Refactor CI & Combine Percy builds

package.json, src/commands/health-check.ts, src/utils/health-checker.ts, yarn.lock
Axios 0.19.0 introduced a change which ignored custom configs (axios/axios#1718) such as `retry-axios`'s `raxConfig`. A fix for this behaviour was recently merged (axios/axios#2207) but there wasn't any release since.
This PR uses a new axios instance instead, thus bypassing the problematic code.
It also fixes a missing default port configuration for the `HealthCheck` command.
Fixes #226
=> build(deps): bump axios from 0.18.1 to 0.19.0

package.json, yarn.lock
This is so we're not depending on a newer version of `follow-redirects` than `axios` is. Now the same version of `follow-redirects` that axios uses is imported into our code (https://github.com/axios/axios/blob/v0.18.1/package.json#L74)
I don't think we need to release for this. It can go out with the next version 👍
=> build: Correct `follow-redirects` dependency version

package.json, yarn.lock
This carries two parallel bug fixes, one which fixes rebuilds on CircleCI (which will help agents CI builds): https://github.com/percy/percy-js/releases/tag/v3.2.1
=> build: Update `percy-js` dep to v3.2.1

.circleci/config.yml, src/commands/exec.ts, src/commands/percy-command.ts, src/commands/start.ts, src/services/agent-service.ts, src/utils/health-checker.ts, test/commands/exec.test.ts, test/commands/snapshot.test.ts, test/commands/start.test.ts, test/helpers/stdout.ts
An issue was brought up where the start and stop commands did not work as expected with the latest version of agent. In fixing that issue, I discovered that our test suite was not finishing and was exiting with a `0` status early.
After digging through CircleCI builds, I am unable to determine when these tests started to not be run in CI. It seem the very fist passing build has a warning about Percy exiting. Previous test runs cannot be viewed due to the junit mocha reporter only saving reports to a file.
- Defaulted healthcheck helper argument to the default port and also made use of the healthcheck endpoint constant.
- Since flags no longer have defaults, we were passing the string `"undefined"` into the detached start process. This was fixed by conditionally setting those flags.
- The …
=> fix: start detached and stop cleanup

src/services/image-snapshot-service.ts, src/services/static-snapshot-service.ts, src/utils/configuration.ts, test/utils/configuration.test.ts
When passing a comma-separated list of globs, sometimes spaces might appear after commas causing the globs to start or end with a space.
I also noticed that valid globs with comma separated lists (commonly used for extensions) would be split incorrectly. i.e. `**/*.{html,htm}` and `**/*.{png,jpg,jpeg}`
Fixes #311 
Created a common `parseGlobs` configuration utility that splits a comma-separated string, while preserving glob lists within `{...}`, and trims whitespace from glob patterns. It also performs the duty of filtering out empty strings.
The configuration unit tests were nested so this could be tested without the extra hooks used in the other config tests.
=> fix: parsing glob strings

.circleci/config.yml, package.json, yarn.lock
#403 removed junit so that our CI would show the full test output. This adds back junit reporting _in addition to_ the default spec output.
Mocha does not accept multiple reporters. There are some reporters that aim to alleviate this by combining common reporters, but I could not find one for spec + junit. Found [mocha-multi](https://github.com/glenjamin/mocha-multi) to allow multiple arbitrary reporters. Although the readme makes it clear that it is a hack, it works to produce a junit file while showing spec output in the CLI.
=> build: add back junit output with mocha-multi

src/percy-agent-client/dom.ts, test/percy-agent-client/dom.test.ts
If the `style` element has innerText that's just line returns, we will incorrectly assume that it has valid CSS content.
This PR will strip whitespace from the ownerNodes innerText.
=> fix: Trim whitespace from CSS ownerNode innerText

src/percy-agent-client/dom.ts
Turns out, innerText can return undefined (for reasons?), so we should ensure there is something present before trying to check the length of it. See this for a reproduction: https://jsfiddle.net/nbpqaz97/1/
Will close #416 #417 (and maybe #415)
=> fix: ensure CSSOM ownerNode content is present

package.json, src/commands/exec.ts, src/configuration/asset-discovery-configuration.ts, src/configuration/configuration.ts, src/services/asset-discovery-service.ts, src/utils/configuration.ts, src/utils/response-cache.ts, test/integration/agent-integration.test.ts, test/utils/response-cache.test.ts
Sometimes the Percy Agent asset discovery service can overload a customers test server, which means sometimes snapshots are missing assets. Right now, we hit their applications test server for each asset at each width. 
Off by default, this PR introduces a way to enable response caching for asset discovery. This is so our asset discovery service only will hit their applications test server for a given asset once (if we get a 200 response). In theory, it should reduce the number of SDK related missing assets (most commonly seen in rails apps)
=> feat: Introduce asset discovery response caching behind flag

package.json, src/commands/exec.ts, test/acceptance/exec.test.js, yarn.lock
We started noticing `[percy] undefined` in the logs whenever the command being executed was not found in the $PATH. This was due to the error object being passed through from the child's `error` handler being interpreted incorrectly by Winston 3.x. Winston attempts to find a `msg` property on the passed object, which is where `undefined` was coming from. Winston does have logic for handling Error instances, but for some reason the error provided by cross-spawn did not get handled like a normal Error.
Fixes #297 
Call `.toString()` on the error to log the error message rather than the error object.
The error this produced was `spawn foobar ENOENT` which might not be obvious to some that it means the command was not found. So I utilized a transitive dependency `which` to perform a …
=> fix: Add better logging for command not found errors

src/services/agent-service.ts, src/services/resource-service.ts, src/services/snapshot-service.ts, test/acceptance/asset-discovery.test.js, test/acceptance/dummy/snapshot-error.js, test/acceptance/helpers/proxy.js
The title is a mouthful, that's for sure. If the child process spawned by agent in `exec` exits while snapshots are processing, it's possible for snapshots to be added to a _finalizing_ build. This will break the rendering pipeline for that build. 
First up was to write an acceptance test that reproduces this behavior. The easiest way would be to have a PercyScript file that loops through snapshots and throws an exception while taking snapshots. Then assert to make sure no snapshots were added to to the build _after_ we've finalized the build. 
Quick solution: As soon as `handleSnaphshot` is called, add a promise to the `snapshotCreationPromises` array. That way any deferred work can still be awaited on (when we're stopping agent).
Better (future) solution: After finalize is called for a …
=> fix: Wait for asset discovery finish when awaiting on snapshot resources in finalize

src/services/response-service.ts
Add check to ensure that requests with 'other' resource type; with an
empty response body are skipped.
The `shouldRequestResolve` in `asset-discovery-service` is used to capture
resource hints in older chromium versions. Cypress versions < 3.5.0 used
chrome 61 whilst above versions have upgraded to 73.
In chrome 61 the resource hint type requests recieved the request
purpose in he header. In future versions, confirmed 73+, this header is
not sent.
In newer chrome versions we can check the request `resourceType`; if of
type 'other' and with an empty response body we can skip the handling of
this request.
=> fix: assets loading issues

src/services/build-service.ts, test/acceptance/exec.test.js
Even if the finalize request fails, we currently print a `finalized build` message (which is not true)
@Robdel12 did the fix, I added a test and sent the error to stderr rather than stdout.
Previously, we were `catch`ing a promise and _then_ logging "successfully." Since the promise thinks the error is "handled" it allows execution to continue. Moving `catch` to be after `then` rather than before will correctly log on a successful response only. Also, rather than mixing `async`/`await` and `then/catch`, this change strictly sticks to `async`/`await` (and uses a `try`/`catch` block instead of promise methods).
=> fix: don't log success on error

src/services/build-service.ts, test/acceptance/exec.test.js
Merged #435 a little fast for some PR feedback
Adds some context to the log output on finalize as @timhaines suggested.
=> fix: add context to log output on finalize error

src/services/agent-service.ts, test/integration/testcases/percy-specific-css.html
We currently loosely inject the Percy CSS style tag right before _a_ closing `</body>` tag. When the page contains some other text that also has a `</body>` (could be a string in JS), the Percy CSS style tag gets incorrectly injected into the wrong place.
Tighten the regular expression to match only the last instance of `</body>` which should appear at the end of the document.
`(<\/body>)` matches the tag in a capturing group  
`(?!.*\1)` negative lookahead ensures there are no other matching groups after the last one  
`/is` will match case insensitive (`i`) and allow `.` to match newlines (`s`)
=> fix: Inject Percy CSS before very last closing body tag

src/services/asset-discovery-service.ts, src/services/resource-service.ts, src/services/response-service.ts, src/utils/logger.ts, src/utils/response-cache.ts
This adds date timestamps to asset discovery logs. Ideally this would be implemented as its own transport for winston, but that would require a lot of refactoring due to how we're passing around the logger. 
This will have to do until we can refactor to the right way.
=> fix: Add timestamps to logs

src/services/asset-discovery-service.ts, src/utils/logger.ts
I forgot to add the timestamp to error logs in #455. This adds those, since they're pretty valuable.
=> fix: Add timestamps to error logs

src/services/asset-discovery-service.ts
This PR makes it so we abort any request that we won't save. This will prevent asset discovery from failing on requests that never resolve (and don't matter to us)
=> fix: Skip requests in asset discovery that will never be saved

src/utils/response-cache.ts, test/integration/agent-integration.test.ts, test/unit/utils/response-cache.test.ts
Builds onto #437 by adding tests
Added a unit test for this since our acceptance tests might be a little flakey due to slow startup times.
This suite was adjusted to account for now requiring a couple other response methods.
Also in this test suite, I replaced instances of `() { return 'foo' }` with `() => 'foo'` except where we explicitly need to reference `this`.
---
Skipped a live site test due to the response being very slow. We have a ticket to remove (and replace if necessary) these live tests, but that should be in another PR. Skipping the failing one for now rather than increasing the timeout to 20 seconds.
=> fix: skip caching empty resources

src/services/image-snapshot-service.ts
#459 brought to light that sometimes image dimensions might be outside of the bounds of our min and max for snapshots.
Clamp both width and height to between 10px - 2000px, but for snapshot options `widths` and `minHeight` only as the image in the DOM should contain the correct width and height.
When we render on our side, the full image should still be captured.
=> fix: clamp image dimensions to min and max for snapshot width and minHeight options

src/percy-agent-client/dom.ts, test/unit/percy-agent-client/dom.test.ts, test/unit/tslint.json
Currently, we only capture iframes during the asset discovery process. In which we only capture the response of the `src` attribute. If an iframe has been interacted with, navigated within, or built with JavaScript, we cannot properly capture that iframe.
This PR aims to solve those limitations
During DOM serialization, we can retrieve the DOM of an iframe using `iframe.contentDocument`. We can then recursively serialize that DOM, and once serialized set the content as a `srcdoc` attribute. The `src` attribute is then removed since it is no longer needed and might cause other issues.
While dealing with iframes, we can also remove iframes from the `<head>`. These iframes typically have no visual presentation and when they do, they often break pages since rerendering causes the browser to …
=> feat: iframe serialization

src/commands/exec.ts, src/configuration/configuration.ts
We have tried this out in support for the past couple months with _great_ success. We're confident enough in this approach to now enable it by default for everyone, which should make the asset discovery process much more reliable and faster.
=> feat: Enable asset discovery network caching by default

src/services/agent-service.ts, test/unit/services/agent-service.test.ts
It might be useful for third part SDKs or even our own SDKs in the future to be able to query the server for some meta information. For now this is limited to build number and URL but could be expanded to include SDK options passed through from the CLI or config file.
Add meta to the healthcheck response and test it.
I noticed that other requests in this file were not awaited on, so they were updated accordingly.
=> feat: add meta information to healthcheck endpoint

src/percy-agent-client/dom.ts, test/unit/percy-agent-client/dom.test.ts
This should hopefully prevent logs like: 
```
browser log: |
ERROR: Could not transform the dom: [object Object]
```
[By using the single arg form of `console.error`](https://developer.mozilla.org/en-US/docs/Web/API/Console/error) it should properly stringify the error & stacktrace for the console.
=> fix: Log DOM transform error so it doesn't end up as [Object object]

src/percy-agent-client/dom.ts, test/unit/percy-agent-client/dom.test.ts
Issue #478 attempted to break the error apart to perserve the stacktrace, but it
looks like it's failing to produce the error message at all (depedning on the
test framework/logging setup).
We're going to call `.toString` on the error to print the message. If the user
wants the stack trace, they will need to open the browser and place a breakpoint
on the error log.
=> fix: Call `toString` on error

src/services/agent-service.ts
Super helpful for debugging:
```bash
[percy] -> widths: 375,1200
[percy] -> minHeight: 1024
[percy] -> enableJavaScript: undefined
[percy] -> requestHeaders: undefined
[percy] -> percyCSS: .percy-only-css-global {
height: 300px;
width: 300px;
background-color: blue;
}```
=> fix: Log out snapshot options in debug logs

src/commands/snapshot.ts, src/commands/upload.ts, src/services/image-snapshot-service.ts, test/unit/commands/snapshot.test.ts, test/unit/commands/upload.test.ts
When honing in your file globs for the `upload` and `snapshot` commands, it can be exhaustive to keep creating new Percy builds. This adds a `--dry-run` (or `-d`) flag to both commands which will not create a new Percy build and print the list of matching paths.
For the `snapshot` command, the snapshot service is responsible for parsing the paths. At that point in the command execution, a build has already been created and the local server started. The resulting paths also have the localhost URL and port attached which is not desirable for printing just the paths. For this command, the glob parsing was copy and pasted into another command method which is called when `--dry-run` is provided.
For the `upload` command, the build is created after glob parsing. So we can safely handle the …
=> feat: snapshot and upload --dry-run flag

src/commands/snapshot.ts, src/services/image-snapshot-service.ts
Tests show that dry run output can sometimes be flakey due to sort order.
Rather than fix the test, this sorts the output. Having the output be sorted will help people iterate on globs so you don't have to search the list to find if something was selected by the glob or not.
Tests were already assuming the output was sorted, so this should result in no more flakes for this test.
=> fix: snapshot & upload sort dry-run output

.circleci/config.yml, README.md, package.json, src/configuration/configuration.ts, src/services/asset-discovery-service.ts, yarn.lock
We have made huge speed & reliability improvements to the asset discovery process. Upping the timeout to 125 for more reliable baseline asset discovery shouldn't be an issue. Especially now that asset discovery response caching is enabled by default for all builds now.
=> fix: Up default network idle timeout to 125

.circleci/orb.yml
Display a link to your home page and the orb source natively in the Orb registry as a clickable link.
Fix: On line 43 - The env_var_name is a string that represents the name of the env var. the "$" is still required to transform it into an env var at the shell.
=> build: Add Home URL and Source Code URL + Fix

src/services/asset-discovery-service.ts
The API will throw an error anyways, so we shouldn't bother trying to create resources or snapshots with non `http` or `https` protocols.
=> fix: Ignore any protocols that aren't `http` or `https`

src/services/asset-discovery-service.ts
If we don't respond the request, it will hang the tab. Since it errored, we should cancel it.
=> fix: Abort requests when caught in an error

src/services/asset-discovery-service.ts
This splits the try/catches up so we can still capture the discovered resources even if the `goto` to the dom snapshot times out.
=> fix: Capture resources even when Puppeteer tab timesout

src/utils/response-cache.ts, test/unit/utils/response-cache.test.ts
CDP returns multiple headers joined by newlines, however `request.respond` (used for cached responses) will hang if there are newlines in headers. This commit normalizes header values as arrays split on newlines.
=> fix: Properly forward headers in asset cache

src/percy-agent-client/dom.ts, test/unit/percy-agent-client/dom.test.ts
Sometimes ads, trackers, and other external scripts may inject iframes with empty documents and a src of `javascript:false`, `javascript:null`, or `javascript:void`. During serialization, these frames might potentially be skipped and left alone if their (empty) documents are not accessible at the time of serialization. This is a problem for asset discovery when JS is disabled because the `src` attribute is still requested, however, not intercepted or resolved since JS is disabled. This causes the asset discovery browser to hang until the `page.goto` method times out.
When the contents of the frame is not accessible in the previous if statement, JS is not enabled, and the frame in question was built with JS, the cloned frame is removed from the cloned DOM.
Frames that are built with JS by …
=> fix(🐛): Remove inaccessible JS frames when serializing

package.json, yarn.lock
Puppeteer 3.2 introduces breaking changes by removing the EventEmitter API and not backporting all EventEmitter methods. This update causes agent to error because `page.removeAllListeners` is no longer a method.
Pinning to 3.1 is a temporary fix until the breaking changes can be accounted for or we migrate away from Puppeteer.
=> fix(📌): Pin Puppeteer to 3.1.x

package.json, yarn.lock
When Puppeteer 3.2 shipped breaking changes, 3.1 was pinned. 3.3 now rolls back those breaking changes so we can safely continue to use 3.x. It is likely that 4.x will re-introduce those breaking changes, but we can figure out a way forward from there (also when their API docs are updated with deprecations and alternatives to event emitter methods).
=> fix(📦): Unpin puppeteer

src/services/response-service.ts
Currently, if someone is serving their app from `localhost:3001` and then serves their assets from `localhost:3002`, we will skip the assets coming from `localhost:3002`. This is because we're taking the port into account for asset discovery right now.
This change removes the port from consideration and captures all assets based on the `hostname` rather than `host`.
=> fix: Capture assets using the same hostname, regardless of port

src/services/asset-discovery-service.ts, src/services/response-service.ts
There is a hidden layer of caching that doesn't cache request responses, but only caches processed responses. So in the past, requests might hang even though they had been processed. This processed cache is not accessible when the request is made due to the entangled nature of the various service classes and callbacks. A new response cache was created with #419 behind a flag, then once proven successful, the flag was turned on with #469. 
However, it appears that this original processed response cache is causing issues when the same URL is expected to return different assets. This should be possible by disabling the response cache, but that flag only affects the new cache.
Pass the cache flag down to the response service so it can skip returning cached responses.
This entire layer of …
=> fix(🐛): Skip all response caches when response caching is disabled

package.json, yarn.lock
There have been a few reports of Puppeteer page crashes that might possibly be related to a recent Puppeteer upgrade. Rather than downgrade back to 2.x again, let's first try upgrading to 5.x 🤞
**Update**: The revisions of Chromium included with puppeteer since 5.0.0 seem to have issues with woff2 requests. Need to investigate further before upgrading to the latest version to see if it's a breaking change or a bug. For now, puppeteer has been pinned to 5.0.0.
=> fix(🐛): upgrade puppeteer to try fixing page crashes

src/percy-agent-client/dom.ts, test/unit/percy-agent-client/dom.test.ts
This attribute causes asset discovery to hang and eventually timeout since we don't scroll the page. Removing the attribute is ideally what we want (to load the iframe).
=> fix: Remove `loading` attributes from cloned iframes

src/services/agent-service.ts, src/services/asset-discovery-service.ts
Sometimes, due to various reasons, the running browser might disconnect from Puppeteer during asset discovery causing a `target closed` error. This error can happen anytime CDP sends a message to the browser, such as enabling JS or setting viewport options. Since it is unhandled it can result in the local server being unable to respond to requests which can then result in request timeouts.
Within asset discovery, move any interaction with the `page` object into an error handler. The various request event registrations do not have to be protected since they are generic event emitter registration methods.
I also noticed that none of the methods within the snapshot handler were protected, which might contribute to the server hanging since it does not respond for unhandled async errors by …
=> fix(🐛): Handle page and snapshot errors

package.json, test/integration/agent-integration.test.ts, yarn.lock
In #539, Puppeteer was pinned to a version that was known not to cause browser crashes. Turns out, that that version also crashes, but only in Docker containers where the default shared memory size is too small to properly run Chromium.
Puppeteer passes along the `--disable-dev-shm-usage` flag to Chromium to avoid this issue, but the current pinned Puppeteer version uses Chromium 83 which has a bug that causes it to ignore that flag. https://bugs.chromium.org/p/chromium/issues/detail?id=1085829
Newer versions of Puppeteer have come out since we pinned it. This PR unpins it again to use the latest version which seems to avoid other issues outlined in #539 such as missing woff assets.
🤞 
---
This also bumps the version so we can quickly release this soon after merging
=> fix(📌): Unpin puppeteer

src/services/process-service.ts
Node 14 will no longer coerce incorrect types given to `writeFileSync`.
The error thrown:
```
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number
```
=> fix: `toString` PID number for `writeFileSync` (second arg requires string)

src/commands/stop.ts
This approach assumes running `percy stop` will happen in the same session. The better approach is to send the POST request anyways & catch if it fails. That way if the server is running (on that path/port) it will get stopped.
=> fix: Don't check if the service is running to stop Percy

package.json
It seems that the lock file has it at 1.4.0 from this commit https://github.com/percy/percy-agent/commit/27127097c8b821fb175c9c8e2e49e31f5a79284c#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR2876
The later versions of colors have an infinite loop added, see references below
References
- https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6?s=09#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R18
- https://www.theverge.com/2022/1/9/22874949/developer-corrupts-open-source-libraries-projects-affected
Locking this to a known good version should give us capability back while migrations to the newer SDK are still underway
=> fix: Lock colors.js to prevent infinite loop
